apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chart: argo-cd
  helmVersion: v2
  repo: https://argoproj.github.io/argo-helm
  version: 2.3.2
  targetNamespace: myns
  valuesContent: |-
    controller:
      extraArgs:
      - --app-resync
      - "60"
      - --gloglevel
      - "4"
    dex:
      enabled: false
